### ISSUE TITLE
this should be configured as prometheus.exporter.unix.localhost.targets

### ISSUE THREAD

**Issue by mikempx** [spartan0x117/flow-by-example#1]
https://github.com/spartan0x117/flow-by-example/blob/2dd03a5266dadec0da0a518b399a671a4652af04/00-first-component-and-standard-library/full-config.river#L22C72-L22C104

prometheus.exporter.unix.`localhost`.targets

**Comment by spartan0x117** [comment]
Good catch! Fix incoming

**Comment by spartan0x117** [comment]
Fixed here: https://github.com/spartan0x117/flow-by-example/commit/8ebeac55bbc4a3ebcd8da8fc57c98ec5b22c433b :smiley:
